export enum recommendationTypes {
  FETCH_RECOMMENDATION_REQUEST = "FETCH_RECOMMENDATION_REQUEST",
  FETCH_RECOMMENDATION_SUCCESS = "FETCH_RECOMMENDATION_SUCCESS",
  FETCH_RECOMMENDATION_FAILUER = "FETCH_RECOMMENDATION_FAILUER",
}
