export enum recommendationTypes {
  FETCH_RECOMMENDATION_REQUEST = "FETCH_RECOMMENDATION_REQUEST",
  FETCH_RECOMMENDATION_SUCCESS = "FETCH_RECOMMENDATION_SUCCESS",
  FETCH_RECOMMENDATION_FAILUER = "FETCH_RECOMMENDATION_FAILUER",
  PUT_RECOMMENDATION_ACCEPT_REQUEST = "PUT_RECOMMENDATION_ACCEPT_REQUEST",
  PUT_RECOMMENDATION_ACCEPT_SUCCESS = "PUT_RECOMMENDATION_ACCEPT_SUCCESS",
  PUT_RECOMMENDATION_ACCEPT_FAILUER = "PUT_RECOMMENDATION_ACCEPT_FAILUER",
  PUT_RECOMMENDATION_REJECT_REQUEST = "PUT_RECOMMENDATION_REJECT_REQUEST",
  PUT_RECOMMENDATION_REJECT_SUCCESS = "PUT_RECOMMENDATION_REJECT_SUCCESS",
  PUT_RECOMMENDATION_REJECT_FAILUER = "PUT_RECOMMENDATION_REJECT_FAILUER",
}
