export enum recommendationTypes {
  FETCH_RECOMMENDATION_REQUEST = "FETCH_RECOMMENDATION_REQUEST",
  FETCH_RECOMMENDATION_SUCCESS = "FETCH_RECOMMENDATION_SUCCESS",
  FETCH_RECOMMENDATION_FAILUER = "FETCH_RECOMMENDATION_FAILUER",
  PUT_RECOMMENDATION_ACCEPT = "PUT_RECOMMENDATION_ACCEPT",
  PUT_RECOMMENDATION_REJECT = "PUT_RECOMMENDATION_REJECT",
}
